---
title: |
       | POLI SCI 403
       | Probability and Statistics
date: last-modified
date-format: long
format: pdf
fontsize: 10pt
geometry:
      - left=.75in
      - textwidth=4.5in
      - marginparsep=.25in
      - marginparwidth=2.25in
---


# Recommended material

## Statistics

### Textbooks

- [Accessible undergrad-level introduction]{.aside} Freedman, David, Robert Pisani, and Roger Purves. 2007. [*Statistics.*](https://wwnorton.com/books/Statistics) New York, NY: Norton

- [Grad-level textbook blending stats and R]{.aside} Imai, Kosuke and Nora Web-Williams. 2022. [*Quantitative Social Science: An Introduction in tidyverse.*](https://press.princeton.edu/books/hardcover/9780691222271/quantitative-social-science) Princeton University Press

- [For complete beginners, light on the math]{.aside} Llaudet, Elena, and Kosue Imai. 2022. [*Data Analysis for Social Science: A Friendly a Practical Introduction.*](https://press.princeton.edu/books/paperback/9780691199436/data-analysis-for-social-science) Princeton University Press

- [Focus on building intuition with no math]{.aside} Kaplan, Daniel, and Randall Pruim. 2023. [*Statistical Modeling: A Fresh Approach*](https://statistical-modeling.netlify.app) (electronic edition)

### Regression

- [Reference textbook for all sorts of regression models]{.aside} Fox, John. 2016. *Applied Regression Analysis and Generalized Linear Models* (Third Edition). Sage

- [Step-by-step regression guide]{.aside} Heiss, Andrew. 2024. [*Program Evaluation*](https://evalsp24.classes.andrewheiss.com/example/regression.html)

### Video lectures

- [Focus on understanding statistical theory concepts]{.aside} King, Gary. [Quantitative Social Science Methods I](https://youtube.com/playlist?list=PL0n492lUg2sgSevEQ3bLilGbFph4l92gH&si=dOClSNcqFPjfv0Xf)

### Parametric models

- [Comprehensive coverage of parametric models]{.aside} Fox, John. 2016. *Applied Regression Analysis and Generalized Linear Models* (Third Edition). Sage

### Missing data

### Partial identification

### Causal inference in experiments

### Causal inference in observational studies

- [Free general textbook]{.aside} Cunningham, Scott. 2021. [*Causal Inference The Mixtape*](https://mixtape.scunning.com)


- [Free general textbook]{.aside} Hungtinton-Klein, Nick. 2022. [*The Effect: An Introduction to Research Design and Causality*](https://theeffectbook.net). Chapman & Hall


## Computing

### Textbooks

- [General introduction to R programming]{.aside} Hadley Wickham, Mine Çetinkaya-Rundel, and Garrett Grolemund. 2023. [*R for Data Science (2e)*](https://r4ds.hadley.nz)

### Tutorials

- [Introduction to Tidyverse]{.aside} Mock, Thomas. 2019. [*A Gentle Introduction to Tidy Statistics in R*](https://posit.co/resources/videos/a-gentle-introduction-to-tidy-statistics-in-r/)