---
title: "Lab 5: Final Project Planning"
author: 
  - FirstName LastName
  - <YourEmail@u.northwestern.edu>
date: October 27, 2025
date-format: "**[D]ue:** MMMM D, YYYY"
format: 
     pdf:
       documentclass: article
fontsize: 12pt
urlcolor: blue
number-sections: true
geometry:
      - left=1in
      - right=1in
      - top=1in
      - bottom=1in
header-includes:
    - \usepackage{setspace}
    - \doublespacing
---

# Overview

```{r setup, include=FALSE}
# Code chunk options
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE,
                      message = FALSE,
                      tidy = FALSE,
                      tidy.opts=list(width.cutoff=80))

# Packages
# Add more packages here if needed
library(tidyverse)

```

## Include a complete reference for the paper you are replicating

## Summarize the paper in 1-2 paragraphs, with special attention to the data and methods used

## Why is this paper important in your field?

## Why is this paper important to your work?

# Replication

::: {.callout-tip}

Nothing here is a binding commitment. I encourage to completely reorient your final paper if you find something worth pursuing, even if it differs from your original plans. As usual, it is a good idea to ask before moving forward with a new plan for your paper.

:::

## Which part of the original paper will be the main component of your direct replication?

## How will you extend upon the fidings of the paper you are replicating?

## Load your paper data into R and show that it works by printing the first ten rows. If you are not in a position to load the data yet, explain the steps needed to do so

## Pick 2-3 variables in the data that are important for your final project. Explain what they measure and how they cover. Are they outcome, explanatory, or control variables? Present data summaries with figures or tables and explain what they imply for the analyses that you will conduct