---
title: "Lab 8: Quasi-Experiments"
author: 
  - FirstName LastName
  - <YourEmail@u.northwestern.edu>
date: November 25, 2024
date-format: "**[D]ue:** MMMM D, YYYY"
format: 
     pdf:
       documentclass: article
fontsize: 12pt
urlcolor: blue
number-sections: true
geometry:
      - left=1in
      - right=1in
      - top=1in
      - bottom=1in
header-includes:
    - \usepackage{setspace}
    - \doublespacing
---

```{r setup, include=FALSE}
# Code chunk options
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE,
                      message = FALSE,
                      tidy = FALSE,
                      tidy.opts=list(width.cutoff=80))

# Packages
library(tidyverse)
library(haven) # read .dta files
library(estimatr) # Design-based estimators
library(broom) # Tidy lm output
library(tinytable) # Print pdf tables
```

# Regression discontinuity

To illustrate the application of RD designs in R, we will use the data referenced in [Cattaneo et al (2020)](https://titiunik.github.io/books/CattaneoIdroboTitiunik2020-CUP-Foundations.pdf).

```{r}

```


## Difference-in-differences